name: 'Terraform Apply'

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "confirm" to apply the Terraform plan'
        required: true
        default: 'confirm'

jobs:
  terraform_apply:
    name: 'Apply'
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.3.0'
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-west-2'

    - name: Download Terraform Plan
      uses: actions/download-artifact@v2
      with:
        name: terraform-plan
        path: infra

    - name: Terraform Apply
      run: |
        cd infra
        terraform apply -auto-approve tfplan
