name: 'Terraform CICD GitHub Actions'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  terraform_plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.3.0'
    
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-west-2'
    
      - name: Terraform Init
        id: init
        run: |
          cd infra
          terraform init

      - name: Terraform Validate
        id: validate
        run: |
          cd infra
          terraform validate

      - name: Terraform Plan
        id: plan
        run: |
          cd infra
          terraform plan
  
  terraform_apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    environment: manual
    needs: terraform_plan
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-west-2'
      
      - name: Terraform Init
        id: init
        run: |
          cd infra
          terraform init

      - name: Terraform Apply
        run: |
          cd infra
          terraform apply -auto-approve
