name: 'Terraform CICD GitHub Actions'

on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.3.0'
    
    - name: Terraform Init
      id: init
      run: |
        cd infra
        terraform init

    - name: Terraform Validate
      id: validate
      run: |
        cd infra
        terraform validate

    - name: Terraform Plan
      id: plan
      run: |
        cd infra
        terraform plan
    
    - name: Manual Approval
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: echo "Awaiting manual approval"

    - name: Terraform Apply
      run: |
        cd infra
        terraform apply -auto-approve
